# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: akigler <akigler@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/22 13:20:54 by akigler           #+#    #+#              #
#    Updated: 2019/07/23 14:59:32 by akigler          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

SRC = *.c

all: $(NAME)

$(NAME):
	gcc -o $(NAME) $(SRC)

clean:
	/bin/rm -f *.o

fclean:
	/bin/rm -f $(NAME)

re: flcean all
